blank_issues_enabled: true
contact_links:
  - name: ScribbleLab Discussions
    url: https://github.com/ScribbleLabApp/ScribbleLab/discussions
    about: Please ask and answer questions here.
  - name: ScribbleLabApp support
    email: n3v1010@gmail.com
    about: support email
